# Generated by Django 2.0.4 on 2018-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0005_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
