# Generated by Django 2.0.4 on 2018-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Person',
        ),
    ]
