# Generated by Django 2.0.4 on 2018-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20180404_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friends', models.ManyToManyField(blank=True, related_name='_facebookuser_friends_+', to='model.FacebookUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='friends',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
