# Generated by Django 2.0.4 on 2018-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20180404_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(blank=True, to='model.InstagramUser')),
            ],
        ),
    ]
